In [1]:
import pandas as pd
from pandas import Series, DataFrame
import os

In [2]:
path = 'cleaned data/'
clean_files = os.listdir(path)

In [3]:
csv = []
for file in clean_files:
    if '.csv' in file:
        name = path + file
        csv.append(name)

In [4]:
frame = pd.read_csv('cleaned data/frame.csv')
frame

Empty DataFrame
Columns: [ID, Spatial Scale, Country Code, Country Name, Technology Name, Metric, Unit, Data Source, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, ...]
Index: []

[0 rows x 334 columns]

In [5]:
# don't use default na, this erroneously converts 'NA' (iso code for Namibia) to a missing value
# I manually input all the default na vals except for 'NA' to prevent this
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
df_list = [frame]
for file in csv:
    file = pd.read_csv(file, keep_default_na=False, na_values=['-1.#IND', '1.#QNAN', '1.#IND', '-1.#QNAN', 
                                                               '#N/A N/A', '#N/A', 'N/A', 'n/a', '<NA>', '#NA', 
                                                               'NULL', 'null', 'NaN', '-NaN', 'nan', '-nan', 
                                                               'None', ''])
    df_list.append(file)

In [6]:
all_tech_df = pd.concat(df_list)
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,1700,1701,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,NaN,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,NaN,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,NaN,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,NaN,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Pumped Hydro Storage_Cumulative Rated Power_CA,National,CA,Canada,Pumped Hydro Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,NaN,NaN,...,4574000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Raw steel production_Annual production_World,Global,World,World,Raw steel production,Annual production,Metric tons,U.S. Geological Survey,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Space Launches_Yearly Launches_UA,National,UA,Ukraine,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
0,Space Launches_Yearly Launches_TM,National,TM,Turkmenistan,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Liquefied natural gas_Annual Production_US,National,US,United States,Liquefied natural gas,Annual Production,Billion cubic feet,U.S. Energy Information Administration,NaN,NaN,...,186.84,707.54,1083.12,1819.4,2389.84,3560.82,NaN,NaN,NaN,NaN
0,Space Launches_Yearly Launches_CO,National,CO,Colombia,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
len(set(all_tech_df['Technology Name']))

203

In [8]:
for x in set(all_tech_df['Technology Name']):
    print(x)

Neoprene Rubber
Refrigerators
Microcomputers
Urea
HEPB3 Vaccine
ROTAC Vaccine
Disk brakes
Polyvinylchloride
Pumped Hydro Storage
Space Launches
Zinc-Based Battery
Nuclear Energy
Beer Production
Ethanolamine
Laundry Dryers
Cadmium Refining
Motor Gasoline
Shale production
Stove
Air-Source Heat Pumps
Natural Gas Power
Nitric Acid
Electro-Chemical Capacitor
Benzene
Marine Energy
Copper Refining
MCV2 Vaccine
Hydrofluoric Acid
Caustic Soda
Styrene
Pentaerythritol
Compressed Air Energy Storage
Microprocessor Clock Speed
Internet Backbone Bandwidth
Herbicide-Tolerant Corn
Lithium-Ion Battery Storage
Ebook reader
Cane Sugar Production
HIB3 Vaccine
Magnesium
Caprolactam
Submarine Cables
Colour TV
DTP1 Vaccine
Heat Thermal Battery Storage
Sand and gravel production (industrial)
Steam ships
YFV Vaccine
Renewable Power
Television
Iron ore
Oil pipeline
Vacuums
Telephones
Internet Traffic
Telegraph Traffic
Lead-Acid Battery Storage
Oil Production
Power steering
Home air conditioning
Liquid Biofuels
PCV3 Vaccine
Lead mine production
Aquaculture production
Crop harvester
Phthalic Anhydride
POL3 Vaccine
Cellphones
Sulphuric Acid
Primary copper production
Synthetic Filaments
Railroad
Liquefied natural gas
Water Heater
Copper Mining
Primary aluminum production
Freezer
Salt production
Videocassette recorder
Natural Gas Production
Hydroelectricity
IPV1 Vaccine
Microwaves
Vinyl Acetate
Passenger Cars
Solar Photovoltaic
Households with only mobile phones (no landlines)
Ethylene Glycol
Potash Fertilizer
Crude Oil
Insect-Resistant Corn
Hydrochloric Acid
Nitrogen Fertilizer
Electronic ignition
Carbon Capture & Sequestration
Sodium
Automatic transmission
Electric Bicycles
Low-Density Polyethylene
Iron
Primary Magnesium
Nuclear weapons
Wet flue gas desulfurization systems
Insect-Resistant Cotton
Amazon Prime users
Magnetic Data Storage
Postal Traffic
Bisphenol A
RCV1 Vaccine
Transistors per Microprocessor
Washing Machines
Stationary Steam Engines
Home computers
Household Internet access
Herbicide-Tolerant Soybeans
Raw steel production
Jet Aircraft
All Biofuels
Phenol
Cement production
Electricity
Fluid Catalytic Cracking Refineries
Biogas
Central heating
BCG Vaccine
Oil Refining Capacity
Phosphate Fertilizer
DTP3 Vaccine
Cable TV
Shotgun Sanger DNA Sequencing
Nickel-Based Battery
Running water
Primary bauxite production
Aniline
Natural gas pipeline
Canals
Ammonia Synthesis
Sensible Heat Storage
Podcasting
Motorcycles
Real-time gross settlement adoption
High-Density Polyethylene
Capture fisheries production
High-speed rail
Dishwashers
Sodium-Based Battery Storage
Solid Biofuels
Rare Earth Mine Production
Flush toilet
HEPBB Vaccine
Methanol
Cyclohexane
Ethyl Alcohol
Radial tires
Tablet
Onshore Wind Energy
Computing Growth
Steam Locomotives
Zinc
Ground Source Heat Pumps
Silver
Electric Range
Processor Performance
Flow Battery Storage
Formaldehyde
Polyester Fiber
Cobalt Mine Production
Concentrated Solar Power
Acrylic Fiber
Sodium Chlorate
Solar Thermal Energy
Lithium Mine Production
Milk production
Polystyrene
Hydrogen Storage
Graphite Mine Production
Offshore Wind Energy
Maleic Anhydride
Nickel production
Compact fluorescent light bulbs
Tin
Smartphone usage
Gold production
Coal Production
Coal Power
MCV1 Vaccine
Desalination capacity
Herbicide-Tolerant Cotton
Paraxylene
Random Access Memory
Nox pollution controls (boilers)
Geothermal Energy
Sand and gravel production (construction)
Vinyl Chloride
Radio
Latent Heat Storage
Acrylonitrile
Social media usage
Ethylene
Public roads
Flywheel Battery Storage
Bicycles
Titanium Sponge

In [9]:
all_tech_df[all_tech_df['Technology Name']=='Cellphones']

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,1700,1701,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
10,Cellphones_Cumulative Total Capacity_World,Global,World,World,Cellphones,Cumulative Total Capacity,MW,IIASA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Cellphones_Total Number_IE,National,IE,Ireland,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cellphones_Total Number_BZ,National,BZ,Belize,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cellphones_Total Number_PY,National,PY,Paraguay,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cellphones_Total Number_BJ,National,BJ,Benin,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Cellphones_Total Number_JP,National,JP,Japan,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,Cellphones_Total Number_VN,National,VN,Vietnam,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,Cellphones_Total Number_SA,National,SA,Saudi Arabia,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Cellphones_Total Number_US,National,US,United States,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Cellphones_Total Number_MX,National,MX,Mexico,Cellphones,Total Number,Number of users,NBER CHAT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
all_tech_df['Technology Name'] = all_tech_df['Technology Name'].str.title()

In [11]:
all_tech_df.insert(8, 'Long Technology Name', all_tech_df['Metric'] + '|' + all_tech_df['Technology Name'])
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Pumped Hydro Storage_Cumulative Rated Power_CA,National,CA,Canada,Pumped Hydro Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Pumped Hydro Storage,NaN,...,4574000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Raw steel production_Annual production_World,Global,World,World,Raw Steel Production,Annual production,Metric tons,U.S. Geological Survey,Annual production|Raw Steel Production,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Space Launches_Yearly Launches_UA,National,UA,Ukraine,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
0,Space Launches_Yearly Launches_TM,National,TM,Turkmenistan,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Liquefied natural gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,Billion cubic feet,U.S. Energy Information Administration,Annual Production|Liquefied Natural Gas,NaN,...,186.84,707.54,1083.12,1819.4,2389.84,3560.82,NaN,NaN,NaN,NaN
0,Space Launches_Yearly Launches_CO,National,CO,Colombia,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
all_tech_df.reset_index(drop=True,inplace=True)
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pumped Hydro Storage_Cumulative Rated Power_CA,National,CA,Canada,Pumped Hydro Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Pumped Hydro Storage,NaN,...,4574000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7568,Raw steel production_Annual production_World,Global,World,World,Raw Steel Production,Annual production,Metric tons,U.S. Geological Survey,Annual production|Raw Steel Production,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7569,Space Launches_Yearly Launches_UA,National,UA,Ukraine,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
7570,Space Launches_Yearly Launches_TM,National,TM,Turkmenistan,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7571,Liquefied natural gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,Billion cubic feet,U.S. Energy Information Administration,Annual Production|Liquefied Natural Gas,NaN,...,186.84,707.54,1083.12,1819.4,2389.84,3560.82,NaN,NaN,NaN,NaN
7572,Space Launches_Yearly Launches_CO,National,CO,Colombia,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
omit = []
for col in all_tech_df.columns:
    if len(col) != 4 or col == 'Unit':
         omit.append(col)
empty_rows = all_tech_df.drop(columns=omit)
empty_rows.dropna(how='all', inplace=True)
na_idx = []
for idx in all_tech_df.index:
    if idx not in empty_rows.index:
        na_idx.append(idx)
all_tech_df.drop(na_idx, inplace=True)
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pumped Hydro Storage_Cumulative Rated Power_CA,National,CA,Canada,Pumped Hydro Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Pumped Hydro Storage,NaN,...,4574000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7568,Raw steel production_Annual production_World,Global,World,World,Raw Steel Production,Annual production,Metric tons,U.S. Geological Survey,Annual production|Raw Steel Production,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7569,Space Launches_Yearly Launches_UA,National,UA,Ukraine,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
7570,Space Launches_Yearly Launches_TM,National,TM,Turkmenistan,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7571,Liquefied natural gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,Billion cubic feet,U.S. Energy Information Administration,Annual Production|Liquefied Natural Gas,NaN,...,186.84,707.54,1083.12,1819.4,2389.84,3560.82,NaN,NaN,NaN,NaN
7572,Space Launches_Yearly Launches_CO,National,CO,Colombia,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
all_tech_df['Metric'] = all_tech_df['Metric'].str.title()

In [15]:
all_tech_df['Metric'] = all_tech_df['Metric'].str.strip()

In [16]:
set(all_tech_df['Metric'])

{'Annual Production',
 'Average Capacity Of Unit Additions',
 'Computing Capacity',
 'Cumulative Length',
 'Cumulative Rated Capacity',
 'Cumulative Rated Power',
 'Cumulative Total Capacity',
 'Installed Capacity',
 'Installed Electricity Capacity',
 'Net Total Capacity',
 'Number Of Weapons',
 'Price',
 'Share Of Acreage',
 'Share Of Boilers',
 'Share Of Households',
 'Share Of Market',
 'Share Of Population',
 'Total Capacity',
 'Total Length',
 'Total Number',
 'Yearly Launches'}

In [17]:
all_tech_df.to_csv('all_tech_version 2.0.csv', index=False)

In [18]:
all_tech_df = all_tech_df[all_tech_df['Metric']!='Price']
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pumped Hydro Storage_Cumulative Rated Power_CA,National,CA,Canada,Pumped Hydro Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Pumped Hydro Storage,NaN,...,4574000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7568,Raw steel production_Annual production_World,Global,World,World,Raw Steel Production,Annual Production,Metric tons,U.S. Geological Survey,Annual production|Raw Steel Production,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7569,Space Launches_Yearly Launches_UA,National,UA,Ukraine,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
7570,Space Launches_Yearly Launches_TM,National,TM,Turkmenistan,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7571,Liquefied natural gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,Billion cubic feet,U.S. Energy Information Administration,Annual Production|Liquefied Natural Gas,NaN,...,186.84,707.54,1083.12,1819.4,2389.84,3560.82,NaN,NaN,NaN,NaN
7572,Space Launches_Yearly Launches_CO,National,CO,Colombia,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
all_tech_df.to_csv('all_tech_version 1.5.csv', index=False)

In [20]:
no_country = []
for tech in set(all_tech_df['Technology Name']):
    countries = list(set(all_tech_df[all_tech_df['Technology Name'] == tech]['Country Name']))
    id_ = list(all_tech_df[all_tech_df['Technology Name'] == tech]['ID'])
    if len(countries) <= 2:
        no_country.extend(id_)

In [21]:
all_tech_w_countrylvl = all_tech_df.set_index('ID', drop=True)
all_tech_w_countrylvl.drop(index=no_country, inplace=True)
all_tech_w_countrylvl

,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,1701,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
ID,,,,,,,,,,,,,,,,,,,,,
Lithium-Ion Battery Storage_Cumulative Rated Power_TG,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lithium-Ion Battery Storage_Cumulative Rated Capacity_TG,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,NaN,...,NaN,190,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Sensible Heat Storage,NaN,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sensible Heat Storage_Cumulative Rated Capacity_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,DOE Global Energy Storage Database,Cumulative Rated Capacity|Sensible Heat Storage,NaN,NaN,...,255000,355000,455000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pumped Hydro Storage_Cumulative Rated Power_CA,National,CA,Canada,Pumped Hydro Storage,Cumulative Rated Power,kW,DOE Global Energy Storage Database,Cumulative Rated Power|Pumped Hydro Storage,NaN,NaN,...,4574000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Raw steel production_Annual production_ZW,National,ZW,Zimbabwe,Raw Steel Production,Annual Production,Metric tons,U.S. Geological Survey,Annual production|Raw Steel Production,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Raw steel production_Annual production_World,Global,World,World,Raw Steel Production,Annual Production,Metric tons,U.S. Geological Survey,Annual production|Raw Steel Production,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Space Launches_Yearly Launches_UA,National,UA,Ukraine,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
Space Launches_Yearly Launches_TM,National,TM,Turkmenistan,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Space Launches_Yearly Launches_CO,National,CO,Colombia,Space Launches,Yearly Launches,Number of objects launched into space,UNOOSA,Yearly Launches|Space Launches,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
all_tech_w_countrylvl.to_csv('all_tech_with_country-level.csv', index=False)