In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
all_tech = pd.read_csv('all_tech.csv')
all_tech

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,1700,1701,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aquaculture_Annual production_World,World,World,World,Aquaculture,Annual production,Metric tons,World Bank,NaN,NaN,...,1.082154e+08,1.122365e+08,1.159116e+08,1.197991e+08,1.225801e+08,NaN,NaN,NaN,NaN,NaN
1,Aquaculture_Annual production_AF,National,AF,Afghanistan,Aquaculture,Annual production,Metric tons,World Bank,NaN,NaN,...,6.150000e+03,7.000000e+03,7.950000e+03,8.000000e+03,8.050000e+03,NaN,NaN,NaN,NaN,NaN
2,Aquaculture_Annual production_AL,National,AL,Albania,Aquaculture,Annual production,Metric tons,World Bank,NaN,NaN,...,4.950000e+03,4.630000e+03,6.458000e+03,6.500000e+03,9.284000e+03,NaN,NaN,NaN,NaN,NaN
3,Aquaculture_Annual production_DZ,National,DZ,Algeria,Aquaculture,Annual production,Metric tons,World Bank,NaN,NaN,...,1.959590e+03,4.467310e+03,5.108420e+03,4.835470e+03,5.435990e+03,NaN,NaN,NaN,NaN,NaN
4,Aquaculture_Annual production_AS,National,AS,American Samoa,Aquaculture,Annual production,Metric tons,World Bank,NaN,NaN,...,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5872,Potash Fertilizer_Annual Production_Tonnes_ZM,National,ZM,Zambia,Potash Fertilizer,Annual Production,Tonnes,UN FAO,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
5873,Nitrogen Fertilizer_Annual Production_Tonnes_ZW,National,ZW,Zimbabwe,Nitrogen Fertilizer,Annual Production,Tonnes,UN FAO,NaN,NaN,...,1.170000e+04,1.230000e+04,1.320000e+04,1.320000e+04,1.320000e+04,NaN,NaN,NaN,NaN,NaN
5874,Phosphate Fertilizer_Annual Production_Tonnes_ZW,National,ZW,Zimbabwe,Phosphate Fertilizer,Annual Production,Tonnes,UN FAO,NaN,NaN,...,2.100000e+03,9.500000e+03,8.100000e+03,8.100000e+03,8.100000e+03,NaN,NaN,NaN,NaN,NaN
5875,Potash Fertilizer_Annual Production_Tonnes_ZW,National,ZW,Zimbabwe,Potash Fertilizer,Annual Production,Tonnes,UN FAO,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN
5876,Liquefied natural gas_Exports_US,NaN,US,United States,Liquefied natural gas,Exports,Billion cubic feet,U.S. Energy Information Administration,NaN,NaN,...,1.868400e+02,7.075400e+02,1.083120e+03,1.819400e+03,2.389840e+03,3560.82,NaN,NaN,NaN,NaN

In [4]:
tech_list = sorted(list(set(all_tech['Technology Name'])))
for x in tech_list:
    print(x)

Acrylic Fiber
Acrylonitrile
Amazon Prime users
Aniline
Aquaculture
Automatic transmission
Automobile
BCG Vaccine
Beer
Benzene
Bicycles
Biofuels
Bisphenol A
CFLs
Cable TV
Caprolactam
Capture fisheries
Cellphones
Cellular phone
Central heating
Coal Power
Coal Production
Cobalt Mine Production
Colour TV
Compressed air energy storage
Computer
Crude Oil
Cyclohexane
DTP1 Vaccine
DTP3 Vaccine
Dishwasher
Disk brakes
Dryer
Ebook reader
Electric Bicycles
Electric Range
Electric power
Electricity
Electricity access
Electro-chemical capacitor
Electronic ignition
Ethanolamine
Ethyl Alcohol
Ethylene
Ethylene 2
Ethylene Glycol
FCC-Refineries
Flow battery
Flush toilet
Flywheel
Formaldehyde
Freezer
Gas Production
Gas pipeline
Graphite Mine Production
HEPB3 Vaccine
HEPBB Vaccine
HIB3 Vaccine
Heat thermal storage
Home air conditioning
Household refrigerator
Households with only mobile phones (no landlines)
Hydro Power
Hydroelectricity
Hydrofluoric Acid
Hydrogen storage
IPV1 Vaccine
Internet
Iron
Jet Aircraft
Landline
Latent heat
Laundry Dryers
Lead-acid battery
Liquefied natural gas
Lithium Mine Production
Lithium-ion battery
Low-Density Polyethylene
MCV1 Vaccine
MCV2 Vaccine
Magnesium
Maleic Anhydride
Methanol
Microcomputer
Microwave
Milk
Motor Gasoline
Motorcycles
NatGas Power
Neoprene Rubber
Nickel-based battery
Nitrogen Fertilizer
Nox pollution controls (boilers)
Nuclear Energy
Nuclear Power
Off-Grid Onshore Wind Energy
Oil Production
Oil Refining Capacity
Oil pipeline
On-Grid Biogas
On-Grid Coal And Peat
On-Grid Geothermal Energy
On-Grid Liquid Biofuels
On-Grid Marine Energy
On-Grid Mixed Hydro Plants
On-Grid Natural Gas
On-Grid Nuclear
On-Grid Offshore Wind Energy
On-Grid Oil
On-Grid Onshore Wind Energy
On-Grid Renewable Hydropower
On-Grid Solar Photovoltaic
On-Grid Solar Thermal Energy
On-Grid Solid Biofuels
PCV3 Vaccine
POL3 Vaccine
Paraxylene
Passenger Cars
Pentaerythritol
Phenol
Phosphate Fertilizer
Phthalic Anhydride
Podcasting
PolyesterFiber
Polyethylene HD
Polyethylene LD
Polystyrene
Polyvinylchloride
Potash Fertilizer
Power steering
Primary Alumninum
Primary Magnesium
Pumped hydro storage
RCV1 Vaccine
ROTAC Vaccine
RTGS adoption
Radial tires
Radio
Railroad
Rare Earth Mine Production
Refined Cane Sugar
Refrigerator
Refrigerators
Renewable Power
Running water
Sensible heat
Shale production
Shipping container port infrastructure
Shotgun Sanger DNA Sequencing
Smartphone usage
Social media usage
Sodium
Sodium Chlorate
Sodium-based battery
Solar Energy
Solar Power
Stationary Steam Engines
Steam Locomotives
Steamships
Stove
Styrene
Tablet
Television
Titanium Sponge
Urea
Vacuum
Videocassette recorder
Vinyl Acetate
Vinyl Chloride
Washer
Washing Machines
Washing machine
Water Heater
Wind Energy
Wind Power
YFV Vaccine
Zinc-based battery

In [ ]:
tech_country_dict = {}
for tech in tech_list:
    tech_country_dict[tech] = len(set(all_tech[all_tech['Technology Name'] == tech]['Country Name']))

In [ ]:
tech_country_dict = dict(sorted(tech_country_dict.items(), key = lambda item: item[1]))
tech_country_dict

In [ ]:
one_country_list = []
mult_country_list = []
for tech in tech_country_dict:
    val = tech_country_dict[tech]
    if val == 1:
        one_country_list.append(tech)
    else:
        mult_country_list.append(tech)
print(len(one_country_list))
print(len(mult_country_list))

In [ ]:
for x in one_country_list:
    print(x)

In [ ]:
mult_country_list

In [ ]:
country_lt_5 = []
country_lt_50 = []
country_lt_250 = []
for tech in tech_country_dict:
    val = tech_country_dict[tech]
    if val > 1 and val < 5:
        country_lt_5.append(tech)
    if val > 4 and val < 50:
        country_lt_50.append(tech)
    if val > 49 and val < 250:
        country_lt_250.append(tech)
print(len(country_lt_5))
print(len(country_lt_50))
print(len(country_lt_250))