In [1]:
import os
import pandas as pd
from pandas import Series, DataFrame
import country_converter as coco

In [2]:
# D12 Africa: Output of Refined Copper, Lead, Tin, and Zinc (in thousand metric tons)
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_112
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_112/MediaObjects/978-1-137-30568-8_112_MOESM1_ESM.xls

In [3]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_309
# D11 South America: Output of Refined Copper, Lead, Tin, And Zinc (in thousands of metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_309/MediaObjects/978-1-137-30568-8_309_MOESM1_ESM.xls

In [4]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_308
# D11 North America: Output of Refined Copper, Lead, Tin, And Zinc (in thousands of metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_308/MediaObjects/978-1-137-30568-8_308_MOESM1_ESM.xls

In [5]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_113
# D12 Asia: Output of Refined Copper, Lead, Tin and Zinc (in thousand metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_113/MediaObjects/978-1-137-30568-8_113_MOESM1_ESM.xls

In [6]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_114
# D12 Oceania: Output of Refined Copper, Lead, Tin, and Zinc (in thousand metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_114/MediaObjects/978-1-137-30568-8_114_MOESM1_ESM.xls

In [7]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_417
# D5 Output of Main Non-Ferrous Metal Ores (in thousands of metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_417/MediaObjects/978-1-137-30568-8_417_MOESM1_ESM.xls
# Europe

In [8]:
os.chdir('/Users/ariana/desktop/historical_tech')

In [13]:
africa = pd.read_excel('raw data/mitchell/978-1-137-30568-8_112_MOESM1_ESM.xls')
africa

,D12,"AFRICA: OUTPUT OF REFINED COPPER, LEAD, TIN, AND ZINC (in thousand metric tons)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Copper,NaN,NaN,NaN,Lead,NaN,NaN,NaN,Tin,Zinc,NaN,NaN
3,NaN,South Africa,Zaire,Zambia,Zimbabwe,Morocco,Namibia,Tunisia,Zambia,Nigeria,Algeria,Zaire,Zambia
4,1913.0,...,...,...,...,...,...,...,...,...,...,...,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2.0,Secondary production (i.e. remelted from scrap...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,NaN,FOOTNOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,1.0,Production of antimonial lead is not included ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_129
# D18 Output of Synthetic Filaments (in thousand metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_129/MediaObjects/978-1-137-30568-8_129_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_130
# D19 Africa: Output of Sulphuric Acid, Hydrochloric Acid, Nitric Acid and Caustic Soda (in thousand metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_130/MediaObjects/978-1-137-30568-8_130_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_132
# D19 Oceania: Output of Sulphuric Acid, Hydrochloric Acid, Nitric Acid and Caustic Soda (in thousand metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_132/MediaObjects/978-1-137-30568-8_132_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_319
# D18 South America: Output of Sulphuric Acid, Hydrochloric Acid, Nitric Acid, and Caustic Soda (in thousands of metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_319/MediaObjects/978-1-137-30568-8_319_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_131
# D19 Asia: Output of Sulphuric Acid, Hydrochloric Acid, Nitric Acid and Caustic Soda (in thousand metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_131/MediaObjects/978-1-137-30568-8_131_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_318
# D18 North America: Output of Sulphuric Acid, Hydrochloric Acid, Nitric Acid, and Caustic Soda (in thousands of metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_318/MediaObjects/978-1-137-30568-8_318_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_435
# D23 Output of Sulphuric Acid (in thousands of metric tons)
# Europe
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_435/MediaObjects/978-1-137-30568-8_435_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_302
# D6 Output of Main Non-Ferrous Metal Ores
# North and South America
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_302/MediaObjects/978-1-137-30568-8_302_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_98
# D7 Asia: Output of Gold and Silver (in metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_98/MediaObjects/978-1-137-30568-8_98_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_99
# D7 Oceania: Output of Gold and Silver (in metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_99/MediaObjects/978-1-137-30568-8_99_MOESM1_ESM.xls

In [ ]:
# https://link.springer.com/referenceworkentry/10.1057/978-1-137-30568-8_97
# D7 Africa: Output of Gold and Silver (in metric tons)
# https://static-content.springer.com/esm/chp%3A10.1057%2F978-1-137-30568-8_97/MediaObjects/978-1-137-30568-8_97_MOESM1_ESM.xls

In [ ]:
#Europe?