In [1]:
import os
import pandas as pd
from pandas import Series, DataFrame
import country_converter as coco

In [2]:
path = '/Users/ariana/desktop/historical_tech'
os.chdir(path)

In [3]:
def read_kurzweil(page_no, tech_name, unit):
    file_name = 'raw data/page' + str(page_no) + '.xls'
    df = pd.read_excel(file_name, header=2, index_col=0, usecols=[0, 1])
    df = df[:-3]
    df = df.transpose()
    df['Data Source'] = 'Kurzweil'
    df['Country Name'] = 'World'
    df['Country Code'] = 'World'
    df['Spatial Scale'] = 'Global'
    df['Metric'] = 'Cumulative Total Capacity'
    df['Technology Name'] = tech_name
    df['Unit'] = unit
    df['ID'] = df['Technology Name'] + '_' + df['Metric'] + '_' + df['Country Code']
    df.set_index('ID', drop=True, inplace=True)
    df.columns.name = None
    file_name = 'cleaned data/' + tech_name + '.csv'
    df.to_csv(file_name)
    return df

In [4]:
# https://www.singularity.com/charts/page64.html
# https://www.singularity.com/images/charts/xls/page64.xls
# Processor Performance

In [5]:
processing_power = read_kurzweil(64, 'Processor Performance', 'Million instructions per second (MIPS)')
processing_power

,1971,1972,1974,1976,1978,1982,1985,1989,1993,1995,...,2000,2001,2002,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,,
Processor Performance_Cumulative Total Capacity_World,0.035,0.08,0.33,0.4,0.9,2.5,5.0,17.0,100.0,800.0,...,4000.0,10000.0,12000.0,Kurzweil,World,World,Global,Cumulative Total Capacity,Processor Performance,Million instructions per second (MIPS)

In [6]:
# https://www.singularity.com/charts/page75.html
# https://www.singularity.com/images/charts/xls/page75.xls
# RAM

In [7]:
ram = read_kurzweil(75, 'Random Access Memory', 'Bits/2000 USD')
ram

,1949,1951,1955,1960,1962,1965,1968,1973,1975,1976,...,2002,2003,2004,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,,
Random Access Memory_Cumulative Total Capacity_World,0.02423,0.03459,0.090545,0.10386,0.21193,1.1623,6.5123,11.388,104.82,170.64,...,31469000.0,36428000.0,93945000.0,Kurzweil,World,World,Global,Cumulative Total Capacity,Random Access Memory,Bits/2000 USD

In [8]:
# https://www.singularity.com/charts/page61.html
# https://www.singularity.com/images/charts/xls/page61.xls
# Microprocessor Clock Speed

In [9]:
microprocessor_clock = read_kurzweil(61, 'Microprocessor Clock Speed', 'Hz')
microprocessor_clock

,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,...,2010,2013,2016,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,,
Microprocessor Clock Speed_Cumulative Total Capacity_World,1350000.0,2060000.0,2140000.0,2290000.0,1940000.0,2410000.0,2630000.0,4070000.0,5190000.0,5890000.0,...,1.151100e+10,1.934800e+10,2.875100e+10,Kurzweil,World,World,Global,Cumulative Total Capacity,Microprocessor Clock Speed,Hz

In [10]:
# https://www.singularity.com/charts/page76.html
# https://www.singularity.com/images/charts/xls/page76.xls
# Magnetic Data Storage

In [11]:
magnetic_data = read_kurzweil(76, 'Magnetic Data Storage', 'Bits/2000 USD')
magnetic_data

,1952,1956,1966,1970,1974,1980,1980,1981,1982,1983,...,2002.25,2003.17,2004.17,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,,
Magnetic Data Storage_Cumulative Total Capacity_World,0.2033,158.8,1437.0,6941.0,12380.0,20040.0,19910.0,15320.0,11310.0,14500.0,...,4.812000e+09,6.552000e+09,1.182000e+10,Kurzweil,World,World,Global,Cumulative Total Capacity,Magnetic Data Storage,Bits/2000 USD

In [12]:
# https://www.singularity.com/charts/page63.html
# https://www.singularity.com/images/charts/xls/page63.xls
# Transistors per Microprocessor

In [13]:
transistors_per_microprocessor = read_kurzweil(63, 'Transistors per Microprocessor', 'Number of transistors per chip')
transistors_per_microprocessor

,1971,1972,1974,1978,1982,1985,1989,1993,1997,1999,2000,2002,2003,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,
Transistors per Microprocessor_Cumulative Total Capacity_World,2250.0,2500.0,5000.0,29000.0,120000.0,275000.0,1600000.0,3100000.0,7500000.0,24000000.0,42000000.0,169000000.0,410000000.0,Kurzweil,World,World,Global,Cumulative Total Capacity,Transistors per Microprocessor,Number of transistors per chip

In [14]:
# https://www.singularity.com/charts/page81.html
# https://www.singularity.com/images/charts/xls/page81.xls
# Internet Backbone Bandwidth

In [15]:
internet_backbone = read_kurzweil(81, 'Internet Backbone Bandwidth', 'Bits/second')
internet_backbone

,1968,1972,1973,1974,1976,1979,1981,1983,1984,1985,...,2002,2003,2004,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,,
Internet Backbone Bandwidth_Cumulative Total Capacity_World,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,56000.0,56000.0,56000.0,1544000.0,...,2.488000e+09,9.952000e+09,9.952000e+09,Kurzweil,World,World,Global,Cumulative Total Capacity,Internet Backbone Bandwidth,Bits/second

In [16]:
# https://www.singularity.com/charts/page70.html
# https://www.singularity.com/images/charts/xls/page70.xls
# Computing Growth

In [17]:
# not stated what year the dollar is indexed to
computing_growth = read_kurzweil(70, 'Computing Growth', 'Calculations per second per $1,000')
computing_growth

,1900,1908,1911,1919,1928,1939,1940,1941,1943,1946,...,1993,1996,1998,Data Source,Country Name,Country Code,Spatial Scale,Metric,Technology Name,Unit
ID,,,,,,,,,,,,,,,,,,,,,
Computing Growth_Cumulative Total Capacity_World,0.000006,0.00013,0.000058,0.001064,0.000699,0.008547,0.01431,0.0463,5.308,0.7981,...,3549000.0,48080000.0,133300000.0,Kurzweil,World,World,Global,Cumulative Total Capacity,Computing Growth,"Calculations per second per $1,000"