In [1]:
import os
import pandas as pd
from pandas import Series, DataFrame
import country_converter as coco

In [2]:
# https://data.nber.org/data-appendix/w15319/
# https://data.nber.org/data-appendix/w15319/FinalCHAT_72909.csv
# https://www.nber.org/system/files/working_papers/w15319/w15319.pdf

In [3]:
os.chdir('/Users/ariana/desktop/historical_tech')

In [4]:
chat = pd.read_csv('raw data/FinalCHAT_72909.csv')

/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/3550461004.py:1: DtypeWarning: Columns (46,51,55,56,60) have mixed types. Specify dtype option on import or set low_memory=False.
  chat = pd.read_csv('raw data/FinalCHAT_72909.csv')

In [5]:
chat_dict = pd.read_excel('raw data/chat_dictionary.xlsx', skipfooter=2)
chat_dict

,VARIABLE NAME,DEFINITION,SOURCE
0,ag_harvester,Number of self‐propelled machines that reap an...,FAOSTAT (2004)
1,ag_milkingmachine,Number of installations consisting of several ...,FAOSTAT (2004)
2,ag_tractor,Number of wheel and crawler tractors (excludin...,FAOSTAT (2004)
3,atm,Number of electromechanical devices that permi...,BIS (various years) and ECB (various years)
4,aviationpkm,Civil aviation passenger‐KM traveled on schedu...,Mitchell (1998)
...,...,...,...
106,pctivprimeenroll,Primary school enrollment rate,Mitchell and Banks
107,pctivsecenroll,Secondary school enrollment rate,Mitchell and Banks
108,pctivprivateinv,Private investment as a share of GDP,Penn World Table (2007)
109,pctivpublicinv,Public investment as a share of GDP,Penn World Table (2007)
110,pctivliteracy,Percent literate (usually calculated on the ba...,Banks (2004)

In [6]:
var_names = list(chat.columns[2:])
var_names

['ag_harvester',
 'ag_milkingmachine',
 'ag_tractor',
 'atm',
 'aviationpkm',
 'aviationtkm',
 'bed_acute',
 'bed_hosp',
 'bed_longterm',
 'cabletv',
 'cellphone',
 'cheque',
 'computer',
 'creditdebit',
 'eft',
 'elecprod',
 'fert_total',
 'internetuser',
 'irrigatedarea',
 'kidney_dialpat',
 'kidney_homedialpat',
 'loom_auto',
 'loom_total',
 'mail',
 'med_catscanner',
 'med_lithotriptor',
 'med_mammograph',
 'med_mriunit',
 'med_radiationequip',
 'newspaper',
 'pctdaysurg_cataract',
 'pctdaysurg_cholecyst',
 'pctdaysurg_hernia',
 'pctdaysurg_lapcholecyst',
 'pctdaysurg_tonsil',
 'pctdaysurg_varicosevein',
 'pcthomedialysis',
 'pctimmunizdpt',
 'pctimmunizmeas',
 'pctirrigated',
 'pctmvbyarea',
 'pest_total',
 'pos',
 'radio',
 'railline',
 'railp',
 'railpkm',
 'railt',
 'railtkm',
 'ship_all',
 'ship_motor',
 'ship_sail',
 'ship_steam',
 'ship_steammotor',
 'shipton_all',
 'shipton_motor',
 'shipton_sail',
 'shipton_steam',
 'shipton_steammotor',
 'spindle_mule',
 'spindle_ring',
 'steel_acidbess',
 'steel_basicbess',
 'steel_bof',
 'steel_eaf',
 'steel_ohf',
 'steel_other',
 'steel_stainless',
 'surg_appendectomy',
 'surg_breastcnsv',
 'surg_cardcath',
 'surg_cataract',
 'surg_cholecyst',
 'surg_corbypass',
 'surg_corinterven',
 'surg_corstent',
 'surg_csection',
 'surg_hernia',
 'surg_hipreplace',
 'surg_hysterectomy',
 'surg_kneereplace',
 'surg_lapcholecyst',
 'surg_mastectomy',
 'surg_pacemaker',
 'surg_prostatetrans',
 'surg_prostatextrans',
 'surg_tonsil',
 'surg_varicosevein',
 'telegram',
 'telephone',
 'transplant_bonemarrow',
 'transplant_heart',
 'transplant_kidney',
 'transplant_liver',
 'transplant_lung',
 'tv',
 'txtlmat_artif',
 'txtlmat_otherraw',
 'txtlmat_synth',
 'txtlmat_totalraw',
 'vehicle_car',
 'vehicle_com',
 'visitorbeds',
 'visitorrooms',
 'xlpopulation',
 'xlrealgdp',
 'pctivprimeenroll',
 'pctivsecenroll',
 'pctivprivateinv',
 'pctivpublicinv',
 'pctivliteracy']

In [7]:
def read_chat(col_num, tech_name, unit='Number in Use', metric='Cumulative total capacity'):
    chat = pd.read_csv('raw data/FinalCHAT_72909.csv', usecols=[0,1,col_num])
    chat.replace('Venezuala', 'Venezuela', inplace=True)
    chat = chat[chat['country_name']!='Indochina']
    country_list = list(set(chat['country_name']))
    chat_df = []
    for country in country_list:
        df = chat[chat['country_name']==country]
        df.set_index('year', drop=True, inplace=True)
        df = df.transpose()
        df['Country Name'] = country
        if country == 'North Vietnam':
            country_code = 'VD'
        elif country == 'South Vietnam':
            country_code = 'VNM'
        elif country == 'Czechoslovakia':
            country_code = 'CSK'
        else:
            country_code = coco.convert(names=country, to='iso2')
        df['Country Code'] = country_code
        df.drop(index='country_name', inplace=True)
        chat_df.append(df)
    chat_all = pd.concat(chat_df)
    chat_all['Data Source'] = 'NBER CHAT'
    chat_all['Spatial Scale'] = 'National'
    chat_all['Unit'] = unit
    chat_all['Metric'] = metric
    chat_all['Technology Name'] = tech_name
    chat_all['ID'] = chat_all['Technology Name'] + '_' + chat_all['Metric'] + '_' + chat_all['Country Code']
    chat_all.set_index('ID', drop=True, inplace=True)
    chat_all.columns.name = None
    omit = []
    for col in chat_all.columns:
        if type(col) != int:
            omit.append(col)
    empty_rows = chat_all.drop(columns=omit)
    empty_rows.dropna(how='all', inplace=True)
    na_idx = []
    for country in chat_all.index:
        if country not in empty_rows.index:
            na_idx.append(country)
    chat_all.drop(na_idx, inplace=True)
    file_name = 'cleaned data/chat_' + tech_name + '.csv'
    chat_all.to_csv(file_name)
    return chat_all

In [8]:
ag_harvester = read_chat(2, 'Crop harvester', metric='Total Number')
ag_harvester

/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Data Source'] = 'NBER CHAT'
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Spatial Scale'] = 'National'
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Unit'] = unit
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Metric'] = metric
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Technology Name'] = tech_name
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['ID'] = chat_all['Technology Name'] + '_' + chat_all['Metric'] + '_' + chat_all['Country Code']

,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,...,2006,2007,2008,Country Name,Country Code,Data Source,Spatial Scale,Unit,Metric,Technology Name
ID,,,,,,,,,,,,,,,,,,,,,
Crop harvester_Total Number_IE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Ireland,IE,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_BZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Belize,BZ,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_EG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Egypt,EG,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_KG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Kyrgyzstan,KG,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_GE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Georgia,GE,NBER CHAT,National,Number in Use,Total Number,Crop harvester
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Crop harvester_Total Number_JP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Japan,JP,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Vietnam,VN,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_SA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Saudi Arabia,SA,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,United States,US,NBER CHAT,National,Number in Use,Total Number,Crop harvester
Crop harvester_Total Number_MX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Mexico,MX,NBER CHAT,National,Number in Use,Total Number,Crop harvester

In [9]:
steam_ships = read_chat(54, 'Steam ships')
steam_ships

/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Data Source'] = 'NBER CHAT'
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Spatial Scale'] = 'National'
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Unit'] = unit
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Metric'] = metric
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['Technology Name'] = tech_name
/var/folders/4_/pdkx43_96v7dxssy4jtd5vyc0000gn/T/ipykernel_22440/1044446949.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chat_all['ID'] = chat_all['Technology Name'] + '_' + chat_all['Metric'] + '_' + chat_all['Country Code']

,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,...,2006,2007,2008,Country Name,Country Code,Data Source,Spatial Scale,Unit,Metric,Technology Name
ID,,,,,,,,,,,,,,,,,,,,,
Steam ships_Cumulative total capacity_IE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Ireland,IE,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Canada,CA,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_IT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Italy,IT,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_CL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Chile,CL,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Norway,NO,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Belgium,BE,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_CU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Cuba,CU,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_DK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Denmark,DK,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Germany,DE,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Sweden,SE,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_NL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Netherlands,NL,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_GR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Greece,GR,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Finland,FI,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,United Kingdom,GB,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Spain,ES,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_FR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,France,FR,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Austria,AT,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_HU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Hungary,HU,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_RU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Russia,RU,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships
Steam ships_Cumulative total capacity_MX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Mexico,MX,NBER CHAT,National,Number in Use,Cumulative total capacity,Steam ships

In [ ]:
telephones = read_chat(91, 'Telephones', metric='Total Number')
telephones

In [ ]:
rail = read_chat(46, 'Railroad', unit='Length of railway open in kilometers',metric='Cumulative Length')
rail

In [ ]:
tv = read_chat(97, 'Television', metric='Total Number')
tv

In [ ]:
# Radio	CHAT database (radio)
radio = read_chat(45, 'Radio', metric='Total Number')
radio

In [ ]:
# Passenger Cars	CHAT (vehicle_car)
cars = read_chat(102, 'Passenger Cars', metric='Total Number')
cars

In [ ]:
# Telegraph Traffic	CHAT (telegram)

telegram = read_chat(90, 'Telegraph Traffic', 'Number of telegrams sent annually', 'Total Number')
telegram

In [ ]:
# Postal traffic	CHAT (mail)

mail = read_chat(25, 'Postal Traffic', 'Number of items mailed/received', metric='Total Number')
mail

In [ ]:
# Cellphones	CHAT (cellphone)

cells = read_chat(12, 'Cellphones', unit='Number of users', metric='Total Number')
cells

In [ ]:
for var_def in chat_dict[chat_dict[chat_dict.columns[0]]=='telephone'][chat_dict.columns[1]]:
    print(var_def)

In [ ]:
for var_idx in chat_dict[chat_dict[chat_dict.columns[0]]=='ag_harvester'].index:
    print(var_idx)

In [ ]:
chat_dict.iloc[89]