In [4]:
import pandas as pd
from pandas import Series, DataFrame
import os

In [10]:
path = '/Users/ariana/desktop/historical_tech'
os.chdir(path)

In [12]:
pd.read_excel('raw data/bp-stats-review-2022-all-data.xlsx')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,bp Statistical Review of World Energy June 2022,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,This workbook contains information presented ...,NaN,NaN,NaN
3,"bp Statistical Review of World Energy, which ...",NaN,NaN,NaN
4,internet at:,NaN,NaN,NaN
...,...,...,...,...
125,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN
127,NaN,NaN,NaN,NaN
128,NaN,NaN,NaN,NaN
129,NaN,NaN,NaN,n