In [1]:
# https://pxweb.irena.org/pxweb/en/IRENASTAT

In [2]:
import pandas as pd
from pandas import Series, DataFrame
import country_converter as coco

In [7]:
df = pd.read_excel('raw data/irena_biogas.xlsx', header=2)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,2000,2001,2002,2003,2004,2005,2006,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Afghanistan,Biogas,On-grid,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,NaN,NaN,Off-grid,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,Albania,Biogas,On-grid,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,NaN,NaN,Off-grid,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,Algeria,Biogas,On-grid,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,Database:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,IRENA Renewable Energy Statistics database,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,Internal reference code:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,ELECCAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN